#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
One-file database setup for Hospital Management System.
Run this on a new PC to:
  1. Create db_config.py (if missing) - you'll be prompted for MySQL credentials
  2. Create the MySQL database
  3. Create all tables (Django migrations)
  4. Seed sample data (admin user, sample doctors/patients/appointments)

Requirements: Python, Django, mysqlclient, MySQL server installed and running.
Usage: python init_database.py
"""

import os
import sys

# ---------------------------------------------------------------------------
# Step 0: Create db_config.py if it doesn't exist
# ---------------------------------------------------------------------------
CONFIG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "db_config.py")

if not os.path.exists(CONFIG_PATH):
    print("\n" + "=" * 60)
    print("  db_config.py not found. Creating it from your input.")
    print("  Enter your MySQL connection details (MySQL must be installed).")
    print("=" * 60 + "\n")
    try:
        db_host = input("MySQL Host [127.0.0.1]: ").strip() or "127.0.0.1"
        db_user = input("MySQL Username [root]: ").strip() or "root"
        db_pass = input("MySQL Password: ").strip()
        db_port = input("MySQL Port [3306]: ").strip() or "3306"
        db_name = input("Database Name [smart_hospital_db]: ").strip() or "smart_hospital_db"
    except EOFError:
        # Non-interactive (e.g. piped): use defaults and empty password
        db_host, db_user, db_pass, db_port, db_name = "127.0.0.1", "root", "", "3306", "smart_hospital_db"
        print("No input - using defaults. Edit db_config.py and run again if needed.")

    config_content = f'''# Auto-generated by init_database.py - edit as needed for this PC
DB_HOST = "{db_host}"
DB_USER = "{db_user}"
DB_PASS = "{db_pass}"
DB_PORT = "{db_port}"
DB_NAME = "{db_name}"
'''
    with open(CONFIG_PATH, "w") as f:
        f.write(config_content)
    print(f"\nCreated {CONFIG_PATH}")
else:
    print("Using existing db_config.py")

# Load config
try:
    import db_config
    db_host = db_config.DB_HOST
    db_user = db_config.DB_USER
    db_pass = db_config.DB_PASS
    db_port = getattr(db_config, "DB_PORT", "3306")
    db_name = getattr(db_config, "DB_NAME", "smart_hospital_db")
except Exception as e:
    print(f"\n[ERROR] Could not load db_config.py: {e}")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Step 1: Create MySQL database
# ---------------------------------------------------------------------------
print("\nStep 1: Connecting to MySQL and creating database...")
try:
    import MySQLdb
    conn = MySQLdb.connect(host=db_host, user=db_user, passwd=db_pass, port=int(db_port))
    cursor = conn.cursor()
    cursor.execute(f"CREATE DATABASE IF NOT EXISTS `{db_name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci")
    conn.close()
    print(f"  Database '{db_name}' ready.")
except ImportError:
    print("  [ERROR] mysqlclient not installed. Run: pip install mysqlclient")
    sys.exit(1)
except Exception as e:
    print(f"  [ERROR] {e}")
    print("  Ensure MySQL server is running and credentials in db_config.py are correct.")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Step 2: Django setup and migrations
# ---------------------------------------------------------------------------
print("\nStep 2: Running Django migrations (creating tables)...")
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "hospital_system.settings")

# Add project root to path
project_root = os.path.dirname(os.path.abspath(__file__))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

import django
django.setup()

from django.core.management import call_command

try:
    call_command("migrate", "--run-syncdb")
    print("  All tables created.")
except Exception as e:
    print(f"  [ERROR] {e}")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Step 3: Seed sample data
# ---------------------------------------------------------------------------
print("\nStep 3: Seeding sample data...")
from datetime import date, time, timedelta
from django.contrib.auth.models import User
from core.models import Patient, Doctor, Appointment, Bill

try:
    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser("admin", "admin@example.com", "admin123")
        print("  Superuser created: username=admin, password=admin123 (change after first login).")

    d1_user, _ = User.objects.get_or_create(username="dr_smith", defaults={"first_name": "John", "last_name": "Smith"})
    d1_user.set_password("dr123")
    d1_user.save()

    d2_user, _ = User.objects.get_or_create(username="dr_jones", defaults={"first_name": "Sarah", "last_name": "Jones"})
    d2_user.set_password("dr123")
    d2_user.save()

    d1, _ = Doctor.objects.get_or_create(user=d1_user, defaults={
        "specialization": "Cardiology",
        "phone": "1234567890",
        "email": "smith@hospital.com",
        "schedule": "Mon-Wed-Fri: 9:00 AM - 2:00 PM",
    })
    d2, _ = Doctor.objects.get_or_create(user=d2_user, defaults={
        "specialization": "Pediatrics",
        "phone": "0987654321",
        "email": "jones@hospital.com",
        "schedule": "Tue-Thu: 10:00 AM - 4:00 PM",
    })

    p1, _ = Patient.objects.get_or_create(name="Alice Wonderland", defaults={
        "age": 28, "gender": "F", "phone": "555-0199", "address": "123 Rabbit Hole Lane", "medical_history": "Asthma",
    })
    p2, _ = Patient.objects.get_or_create(name="Bob Builder", defaults={
        "age": 45, "gender": "M", "phone": "555-2020", "address": "Construction Way #4", "medical_history": "No allergies",
    })

    today = date.today()
    Appointment.objects.get_or_create(patient=p1, doctor=d1, date=today + timedelta(days=1), time=time(10, 0), defaults={"status": "Scheduled"})
    a2, _ = Appointment.objects.get_or_create(patient=p2, doctor=d2, date=today, time=time(14, 0), defaults={"status": "Completed"})

    if not Bill.objects.filter(patient=p2, appointment=a2).exists():
        Bill.objects.create(patient=p2, appointment=a2, consultation_fee=500.00, medicine_charges=150.00, other_charges=20.00, payment_status="Paid")

    print("  Sample data seeded.")
except Exception as e:
    print(f"  [WARN] Seeding failed (tables are still created): {e}")

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
print("\n" + "=" * 60)
print("  Database setup complete. You can run the app with run_app.bat")
print("  or: python manage.py runserver")
print("=" * 60 + "\n")
