# Generated by Django 6.0.3 on 2026-03-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10),
        ),
    ]
